all:
  hosts:
    diversion: # TEST forward proxy - test-forwardproxy.nrs.bcgov
      ansible_host: diversion.dmz
    nrcpod01: # TEST forward proxy - test-logproxy.nrs.bcgov
      ansible_host: nrcpod01.dmz      
    conversion: # PROD forward proxy - forwardproxy.nrs.bcgov
      ansible_host: conversion.dmz
    freight: # DMZ podman host
      ansible_host: freight.bcgov
    payload: # DMZ podman host
      ansible_host: payload.bcgov
      
  vars:
    ansible_connection: ssh
    ansible_user: "{{ ssh_user }}"
    ansible_password: "{{ ssh_pass }}"
    ansible_become_pass: "{{ ansible_become_pass }}"