---
# TEST forward proxy - test-forwardproxy.nrs.bcgov
- hosts: diversion

  # Include Ansible vault file variables
  # ------------------------------------
  vars_files:
    - ~/.vault/vault.yml

  roles:
    - name: 00-util/ansible-apache-pre-reqs
    - name: forward-proxy/srv-diversion-tiny