- name: Setup, copy over configuration files
  copy:
    src: "files/conf/"
    dest: "/sw_ux/podman/tinyproxy/conf/"
    follow: no
    group: wwwadm
    owner: wwwadm
    mode: 0644
  become: yes
  become_user: wwwadm

- name: Log into OCIO Artifactory container registry
  containers.podman.podman_login:
    username: "{{ artifactory_username }}"
    password: "{{ artifactory_password }}"
    registry: "artifacts.developer.gov.bc.ca/d245-tinyproxy/"
  become: yes
  become_user: wwwadm 

- name: Pull an image
  containers.podman.podman_image:
    name: tinyproxy
    tag: latest
  become: yes
  become_user: wwwadm

- name: Create tinyproxy container, but not run/start because that will be done via systemd
  containers.podman.podman_container:
    name: tinyproxy
    image: artifacts.developer.gov.bc.ca/d245-tinyproxy/tinyproxy
    state: created
    volume: /sw_ux/podman/tinyproxy/conf/:/usr/local/etc/tinyproxy/:z
    network: host
  become: yes
  become_user: wwwadm
 
# The following is necessary because Ansible currently lacks podman/systemd support
- name: Generate systemd unit file
  command: podman generate systemd --new --files --name tinyproxy
  become: yes
  become_user: wwwadm
  args:
    chdir: /sw_ux/podman/tinyproxy/

- name: Create a symbolic link
  ansible.builtin.file:
    src: /sw_ux/podman/tinyproxy/*.service
    dest: /apps_ux/wwwadm/.config/systemd/user/
    owner: wwwadm
    group: wwwadm
    state: link
  become: yes
  become_user: wwwadm

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: container-tinyproxy
    enabled: yes
    scope: user
  become: yes
  become_user: wwwadm