name: Build Bitnami Jenkins Image

on:
  workflow_dispatch:
    inputs:
      jenkins_tag:
        description: "Bitnami Jenkins image tag (e.g. 2.516.2-debian-12-r0)"
        required: true
        default: "2.516.2-debian-12-r0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Find commit for Jenkins image tag
        id: find_commit
        run: |
          IMAGE_TAG="${{ github.event.inputs.jenkins_tag }}"

          echo "Looking for commit associated with image tag: $IMAGE_TAG"

          # Search commit logs for the release message
          COMMIT=$(git ls-remote https://github.com/bitnami/containers.git HEAD | cut -f1)
          git clone --filter=tree:0 https://github.com/bitnami/containers.git bitnami-containers
          cd bitnami-containers

          # Search for commit releasing this image version
          MATCHING_COMMIT=$(git log --pretty=format:"%H %s" --grep="$IMAGE_TAG" | head -n 1 | cut -d' ' -f1)

          if [[ -z "$MATCHING_COMMIT" ]]; then
            echo "❌ Could not find commit for Jenkins tag $IMAGE_TAG"
            exit 1
          fi

          echo "✅ Found commit: $MATCHING_COMMIT"
          echo "commit=$MATCHING_COMMIT" >> "$GITHUB_OUTPUT"

      - name: Sparse checkout bitnami/jenkins at exact commit
        run: |
          COMMIT=${{ steps.find_commit.outputs.commit }}

          # Remove the dir if it exists
          if [ -d "bitnami-containers" ]; then
            echo "⚠️ Directory 'bitnami-containers' already exists. Removing it..."
            rm -rf bitnami-containers
          fi

          git clone --no-checkout https://github.com/bitnami/containers.git bitnami-containers
          cd bitnami-containers

          git sparse-checkout init --cone
          git sparse-checkout set bitnami/jenkins
          git checkout "$COMMIT"

          echo "✅ Checked out commit $COMMIT with only bitnami/jenkins"

      - name: Build Bitnami Jenkins image with version and latest tags
        run: |
          cd bitnami-containers/bitnami/jenkins/2/debian-12

          IMAGE_NAME=ghcr.io/${{ github.repository }}/jenkins
          TAG=${{ github.event.inputs.jenkins_tag }}

          docker build \
            -t "$IMAGE_NAME:$TAG" \
            -t "$IMAGE_NAME:latest" \
            .


      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push Jenkins image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/jenkins
          TAG=${{ github.event.inputs.jenkins_tag }}

          echo "📦 Tagging image as:"
          echo " - $IMAGE_NAME:$TAG"
          echo " - $IMAGE_NAME:latest"

          # Tag with version and latest
          docker tag jenkins "$IMAGE_NAME:$TAG"
          docker tag jenkins "$IMAGE_NAME:latest"

          # Push both tags
          docker push "$IMAGE_NAME:$TAG"
          docker push "$IMAGE_NAME:latest"
