name: Build Bitnami Jenkins Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - ".**"
      - "**.md"
      - "**.yml"
      - "**.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Clone bitnami/containers
        run: |
          git clone --no-checkout https://github.com/bitnami/containers.git bitnami-containers
          cd bitnami-containers
          git sparse-checkout init --cone
          git sparse-checkout set bitnami/jenkins
          git checkout main

      - name: Build Bitnami Jenkins image
        run: |
          cd bitnami-containers/bitnami/jenkins/2/debian-12
          docker build -t ghcr.io/${{ github.repository }}/jenkins:${IMAGE_TAG} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Jenkins image to this repo's GHCR
        run: |
          docker
